stages:
  - build

job:
  stage: build
  script:
  - echo "Release build..."
  - C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe /consoleloggerparameters:ErrorsOnly /property:Configuration=Release /verbosity:quiet "CS411Crystal\BlackboardArchiveExtractor.csproj"
  tags: 
  except:
  - tags